apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: your-chart-app
  namespace: argocd
spec:
  project: default

  source:
    repoURL: 'https://github.com/sidhuni/argo.git'
    targetRevision: main        # or master or branch name
    path: your-chart    # folder where Chart.yaml exists
    helm:
      releaseName: chart-release

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
